project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Explaining Text Classification Models with LIME:Stability and Interpretability in NLP"
  author:
    - Jinze Shi (js6605)
    - Xiying  Mao (xm2335)
  repo-url: https://github.com/Rain-Shi/lime-nlp-stability.git
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - modeling.qmd
    - bert_modeling.qmd
    - lime.qmd
    - perturbation.qmd
    - visualization.qmd
    - conclusion.qmd


format:
  html:
    theme: cosmo
    code-fold: true


